# This file was generated by GoReleaser. DO NOT EDIT.
cask "dw-terminal" do
  version "0.7.11"

  on_macos do
    sha256 "47003e39fe2f7678ab6c6cd4be59037c6d075ff10ec1decdff09dc08faeaa011"
    url "https://github.com/brightman-ai/deepwork-terminal/releases/download/v#{version}/dw-terminal_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "d86b5d4f04f7ebdcf3640fc96e64e269323116f9052000f652cceeab53b96392"
      url "https://github.com/brightman-ai/deepwork-terminal/releases/download/v#{version}/dw-terminal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a0910e129a1fb86ecd56c316c4c99cbb276107db58729bcbb540ac5009ea37c"
      url "https://github.com/brightman-ai/deepwork-terminal/releases/download/v#{version}/dw-terminal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dw-terminal"
  desc "Standalone web terminal with auth, Cloudflare tunnel, and an embedded Vue frontend"
  homepage "https://github.com/brightman-ai/deepwork-terminal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dw-terminal"

  # No zap stanza required

end
