# This file was generated by GoReleaser. DO NOT EDIT.
cask "dw-terminal" do
  version "0.11.0"

  on_macos do
    sha256 "3caf39d5ec640b9c8a5085dec2544fcdbbe417e4e7d5c568803e4d056b83d137"
    url "https://github.com/brightman-ai/deepwork-terminal/releases/download/v#{version}/dw-terminal_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "64ec025cb18cfcb7e5612835e09a13af67071beffe1e95eedcbfb2481b545b13"
      url "https://github.com/brightman-ai/deepwork-terminal/releases/download/v#{version}/dw-terminal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9085b90b3a4317d1782c1d3eafe212e1e2d50d8f9001440e0e6c7a5e0e7f3266"
      url "https://github.com/brightman-ai/deepwork-terminal/releases/download/v#{version}/dw-terminal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dw-terminal"
  desc "Standalone web terminal with auth, Cloudflare tunnel, and an embedded Vue frontend"
  homepage "https://github.com/brightman-ai/deepwork-terminal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dw-terminal"

  # No zap stanza required

end
