# This file was generated by GoReleaser. DO NOT EDIT.
cask "dw-terminal" do
  version "0.11.2"

  on_macos do
    sha256 "66793a6af3d283ae11deb4e44a2659444ec8eb982864b58c80c2f1a4817a9c31"
    url "https://github.com/brightman-ai/deepwork-terminal/releases/download/v#{version}/dw-terminal_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "3b464b36122ef393a40f268785411ac300af8b2e1cc576170463801e67815e6f"
      url "https://github.com/brightman-ai/deepwork-terminal/releases/download/v#{version}/dw-terminal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8192b7be2657d6d5d1b28719ebd8d369e63af4c86815c453090dbc7fdcb3edf9"
      url "https://github.com/brightman-ai/deepwork-terminal/releases/download/v#{version}/dw-terminal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dw-terminal"
  desc "Standalone web terminal with auth, Cloudflare tunnel, and an embedded Vue frontend"
  homepage "https://github.com/brightman-ai/deepwork-terminal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dw-terminal"

  # No zap stanza required

end
